'use client';


export default function Regulamin() {
  return (
    <main style={{ minHeight: '100vh', background: '#faf7fc', padding: '0 0 60px' }}>
      <style dangerouslySetInnerHTML={{ __html: `
        .rg-wrap{max-width:760px;margin:0 auto;padding:0 20px;font-family:'Nunito',sans-serif;color:#3a3448;line-height:1.7;}
        .rg-hero{background:linear-gradient(135deg,#a78dd9 0%,#ca4490 100%);padding:44px 20px 40px;text-align:center;margin-bottom:36px;}
        .rg-hero h1{font-family:'Quicksand',sans-serif;font-weight:700;font-size:34px;color:#fff;margin:0 0 6px;}
        .rg-hero p{color:#f3e9f5;font-size:15px;margin:0;}
        .rg-back{display:inline-block;margin:24px 0 0;color:#fff;text-decoration:none;font-weight:700;font-size:14px;opacity:.95;}
        .rg-back:hover{text-decoration:underline;}
        .rg-wrap h2{font-family:'Quicksand',sans-serif;font-weight:700;font-size:20px;color:#8a3a72;margin:34px 0 12px;padding-top:14px;border-top:2px solid #efe6f4;}
        .rg-wrap p{margin:0 0 14px;}
        .rg-intro{background:#fff;border-radius:16px;padding:22px 24px;box-shadow:0 4px 16px rgba(202,68,144,.06);margin-bottom:10px;}
        .rg-date{display:inline-block;background:#f3e9f5;color:#8a3a72;font-weight:700;font-size:13px;padding:5px 12px;border-radius:99px;margin:0 0 16px;}
        .rg-wrap ol{margin:0 0 14px;padding-left:22px;}
        .rg-wrap ol li{margin-bottom:11px;}
        .rg-wrap a{color:#ca4490;font-weight:600;}
        .rg-contact{background:#fff;border-radius:14px;padding:18px 22px;margin:28px 0 0;text-align:center;box-shadow:0 4px 16px rgba(202,68,144,.06);}
        .rg-contact a{color:#ca4490;font-weight:700;}
        @media(max-width:560px){.rg-hero h1{font-size:27px;}.rg-wrap h2{font-size:18px;}}
      ` }} />

      <div className="rg-hero">
        <h1>Regulamin</h1>
        <p>easygo-english.pl · easywonders.pl</p>
        <a href="/" className="rg-back">← Wróć do EasyWonders</a>
      </div>

      <div className="rg-wrap">
        <div className="rg-intro">
          <span className="rg-date">Data obowiązywania: 12.08.2026 r.</span>
          <p>Regulamin, który czytasz, dotyczy udostępniania Treści cyfrowych, jak i Usług cyfrowych, dostępnych na stronie internetowej pod adresem easygo-english.pl oraz na platformie z ćwiczeniami interaktywnymi pod adresem easywonders.pl.</p>
          <p>Dla ułatwienia w dalszej części Regulaminu moduł strony, która umożliwia zakup produktów, będziemy nazywać „Sklepem”.</p>
          <p>W tym Regulaminie znajdziesz między innymi: zasady zawarcia umowy, warunki umowy, postanowienia dotyczące konsumentów oraz informacje o sposobie reklamacji i odstąpienia od umowy. Umowa może być zawarta poprzez złożenie Zamówienia na stronie internetowej Sklepu. Informacje dostępne na stronie Sklepu i w tym Regulaminie nie stanowią oferty w rozumieniu przepisów Kodeksu cywilnego, ale zaproszenie do zawarcia umowy.</p>
          <p style={{margin:0}}>W każdej sprawie związanej z zakupami i funkcjonowaniem Sklepu możesz skontaktować się z nami pod adresem e-mail <a href="mailto:info@easygo-english.pl">info@easygo-english.pl</a> i/lub pod numerem telefonu: +48 509 570 906.</p>
        </div>

        <h2>Kto udostępnia Treść cyfrową lub Usługę cyfrową?</h2>
        <p>Usługodawcą jest właścicielka sklepu: Rozalia Lakhwani prowadząca działalność gospodarczą pod nazwą Rozalia Lakhwani EasyGo z miejscem prowadzenia działalności gospodarczej pod adresem Muzyczna 43b, 02-862 Warszawa, NIP 9512532874, REGON 520948370.</p>
        <h2>Kogo dotyczy ten Regulamin?</h2>
        <p>Regulamin dotyczy osób, które korzystają z udostępnionych Treści cyfrowych lub Usług cyfrowych w ramach Sklepu, odbiorcami są zarówno konsumenci, przedsiębiorcy na prawach konsumenta, jak i pozostali przedsiębiorcy.</p>
        <h2>Wyjaśnienie definicji</h2>
        <p>Usługodawca: Rozalia Lakhwani prowadząca działalność gospodarczą pod nazwą Rozalia Lakhwani EasyGo z miejscem prowadzenia działalności gospodarczej pod adresem Muzyczna 43b, 02-862 Warszawa, NIP 9512532874, REGON 520948370.</p>
        <p>Sklep: Serwis internetowy dostępny pod adresem easygo-english.pl oraz platforma z ćwiczeniami interaktywnymi dostępna pod adresem easywonders.pl, na której świadczona jest Subskrypcja.</p>
        <p>Formularz zamówienia: Formularz służący do złożenia zamówienia na Treści i Usługi cyfrowe. Uzupełnienie formularza wymaga dodania wybranych Treści lub Usług cyfrowych do Koszyka, wybrania sposobu płatności oraz uzupełnienia danych klienta niezbędnych do zakupu.</p>
        <p>Klient: To Konsument, Przedsiębiorca lub Przedsiębiorca na prawach konsumenta. Klientem jest podmiot będący osobą fizyczną lub osobą prawną, który dokonuje zakupu Treści lub Usługi cyfrowej.</p>
        <p>Przedsiębiorca: To osoba prawna lub osoba fizyczna, prowadząca działalność gospodarczą, która dokonuje zakupu Treści lub Usługi cyfrowej, zawierając Umowę, a z treści tej Umowy wynika, że jest ona bezpośrednio związana z wykonywaną przez Przedsiębiorcę działalnością gospodarczą i posiada dla Przedsiębiorcy charakter zawodowy.</p>
        <p>Konsument: To osoba fizyczna dokonująca z Usługodawcą czynności prawnej niezwiązanej bezpośrednio z jej działalnością gospodarczą lub zawodową.</p>
        <p>Przedsiębiorca na prawach konsumenta: To osoba fizyczna prowadząca działalność gospodarczą, dokonująca zakupu Treści lub Usługi cyfrowej, która jest bezpośrednio związana z działalnością gospodarczą tej osoby, ale z treści Umowy wynika, że Umowa ta nie posiada dla przedsiębiorcy charakteru zawodowego (np. na podstawie danych o przedmiocie działalności gospodarczej udostępnionych w CEIDG).</p>
        <p>Użytkownik: To Klient lub osoba niebędąca Klientem Sklepu odwiedzająca Sklep i mogąca zapoznać się z Treściami w obrębie Sklepu lub osoba, która umieściła w Sklepie Treść.</p>
        <p>Konto Klienta: To indywidualny dostęp Klienta na stronie Sklepu określany nazwą użytkownika oraz hasłem w postaci ciągu znaków zabezpieczających dostęp do konta.</p>
        <p>Treść cyfrowa: To dane wytworzone i dostarczane w postaci cyfrowej.</p>
        <p>Usługa cyfrowa: To usługa pozwalająca na wytwarzanie, przetwarzanie i przechowywanie danych lub dostęp do nich w postaci cyfrowej lub usługa pozwalająca na wspólne korzystanie z danych w postaci cyfrowej, które zostały przesłane lub wytworzone przez konsumenta lub innych użytkowników tej usługi, lub inne formy interakcji przy pomocy takich danych.</p>
        <p>Produkt: To indywidualny dostęp Klienta do Treści cyfrowej lub Usługi cyfrowej, która jest przedmiotem Umowy, i który jest przyznany na określony czas zgodny z Umową. Opis Produktu oraz ceny brutto są dostępne na stronie Sklepu przy prezentowanej Treści lub Usłudze cyfrowej.</p>
        <p>Subskrypcja: Odpłatna Usługa cyfrowa polegająca na zapewnieniu Klientowi dostępu do Treści i Usług cyfrowych oznaczonych jako dostępne w ramach Subskrypcji, świadczona przez czas nieoznaczony, w której Cena pobierana jest cyklicznie (w okresach miesięcznych lub rocznych, zgodnie z wybranym przez Klienta wariantem) w formie płatności odnawialnej, aż do momentu rezygnacji z Subskrypcji przez Klienta lub jej zakończenia zgodnie z Regulaminem.</p>
        <p>Okres rozliczeniowy: Powtarzalny okres (miesiąc lub rok, zgodnie z wybranym wariantem Subskrypcji), za który pobierana jest opłata z tytułu Subskrypcji.</p>
        <p>Płatność cykliczna (odnawialna): Sposób płatności, w którym Klient upoważnia operatora płatności do automatycznego, cyklicznego pobierania opłaty za kolejne Okresy rozliczeniowe Subskrypcji, bez konieczności każdorazowego zatwierdzania płatności przez Klienta.</p>
        <p>Konto Lektora: Rodzaj Subskrypcji przeznaczony dla Klientów prowadzących działalność edukacyjną (np. nauczycieli, lektorów, szkół językowych), w ramach której Klient (Lektor) wykupuje określoną liczbę miejsc (dostępów) dla swoich Uczniów i przypisuje do nich wskazane przez siebie adresy e-mail.</p>
        <p>Uczeń: Osoba, której Lektor przypisał dostęp do Treści i Usług cyfrowych w ramach Konta Lektora, poprzez wskazanie jej adresu e-mail. Uczeń korzysta z dostępu w okresie obowiązywania Subskrypcji Lektora.</p>
        <p>Cena: Wskazane w polskich złotych wynagrodzenie wraz z podatkami należne Usługodawcy z tytułu wykonania Umowy przez Usługodawcę.</p>
        <p>Usługa elektroniczna: Świadczenie usług drogą elektroniczną, w rozumieniu Ustawy z dnia 18 lipca 2002 r. o świadczeniu usług drogą elektroniczną (Dz.U. z 2020 r. poz. 344 z późn. zm.), przez Usługodawcę na rzecz Klienta za pośrednictwem strony internetowej Sklepu.</p>
        <p>Wymagania techniczne: Są to minimalne wymagania techniczne, których spełnienie jest niezbędne do współpracy z systemem teleinformatycznym, którym posługuje się Sklep, w tym zawarcia Umowy o Świadczenie Usług lub Umowy tj.: komputer, laptop lub inne urządzenie multimedialne z dostępem do Internetu; dostęp do poczty elektronicznej; Klient musi posiadać ważny/aktywny adres e-mail, a także w określonych przypadkach klawiaturę lub inne urządzenie wskazujące, umożliwiające poprawne wypełnienie formularzy elektronicznych; dostęp do aktualnej przeglądarki internetowej: Mozilla Firefox, Internet Explorer, Opera, Google Chrome, Safari.</p>
        <p>Umowa: To umowa zawierana pomiędzy Usługodawcą a Klientem za pośrednictwem Sklepu lub w inny sposób, w szczególności poprzez przesłanie Zamówienia na adres e-mail Usługodawcy i opłacenie złożonego Zamówienia przez Klienta, w ramach której Usługodawca zobowiązuje się do udostępnienia Treści lub Usługi cyfrowej, a Klient do zapłaty Ceny. Umowa zawierana jest z chwilą przesłania potwierdzenia przyjęcia Zamówienia przez Usługodawcę.</p>
        <p>Umowa o świadczenie usług: Zawarta pomiędzy Usługodawcą a Klientem, której przedmiotem jest świadczenie Usług Elektronicznych udostępnianych za pośrednictwem Sklepu, na warunkach określonych w niniejszym Regulaminie.</p>
        <p>Zamówienie: To oświadczenie woli Klienta składane za pośrednictwem formularza zamówienia, zmierzające do zawarcia Umowy na odległość, które jest składane z wykorzystaniem środków porozumiewania się na odległość, w szczególności strony internetowej Sklepu, co do którego Klient składa ofertę zawarcia Umowy dotyczącą Treści cyfrowej lub Usługi cyfrowej i kierowane jest do Usługodawcy oraz w ramach którego Klient podaje swoje dane niezbędne dla ewentualnego zawarcia i wykonania Umowy. Złożenie Zamówienia możliwe jest także poprzez przesłanie go na adres e-mail Usługodawcy wskazany w Regulaminie.</p>
        <p>Koszyk: Usługa Elektroniczna udostępniana Klientowi Sklepu polegająca na umożliwieniu mu złożenia Zamówienia Treści lub Usługi cyfrowej, wpisaniu kodów rabatowych umożliwiających obniżenie Ceny na zasadach określonych odrębnymi umowami/regulaminami, wyświetleniu podsumowania dot. Ceny poszczególnych Treści i Usług cyfrowych.</p>
        <p>Promocje: Szczególne warunki zawarcia Umowy proponowane przez Usługodawcę w określonym konkretnie czasie, z których Klient może skorzystać na określonych przez Usługodawcę zasadach np. obniżenie ceny Treści lub Usługi cyfrowej.</p>
        <p>Ustawa o prawach konsumenta: Ustawa z dnia 30 maja 2014 r. o prawach konsumenta (Dz.U. 2020 r. poz. 287 z późn. zm.).</p>
        <p>Regulamin: Niniejszy dokument określający zasady zawierania Umów oraz zasady świadczenia i korzystania z usług, w tym Usług Elektronicznych, udostępnianych przez Usługodawcę za pośrednictwem Sklepu na rzecz Klientów. Regulamin określa prawa i obowiązki Klienta Sklepu będącego Konsumentem, Przedsiębiorcą lub Przedsiębiorcą na prawach konsumenta.</p>
        <p>Cena początkowa: Pierwsza Cena Produktu, w której pojawił się Produkt w Sklepie.</p>
        <p>Najniższa cena z ostatnich 30 dni przed obniżką: Najniższa Cena, w której produkt był dostępny w Sklepie w ciągu ostatnich 30 dni przed obniżką.</p>
        <p>Cena promocyjna: Cena Produktów w Sklepie po obniżeniu w związku z ogłoszeniem przez Usługodawcę Promocji.</p>
        <p>Punkt kontaktowy: To sposób umożliwiający Usługodawcy bezpośrednią komunikację drogą elektroniczną z organami państw członkowskich, Komisją i Radą Usług Cyfrowych oraz z Użytkownikami.</p>
        <p>Usługa hostingu: To usługa polegająca na przechowywaniu informacji przekazanych przez Użytkownika oraz na jego żądanie. Usługa hostingu To Usługodawca, czyli Rozalia Lakhwani prowadząca działalność gospodarczą pod nazwą Rozalia Lakhwani EasyGo z miejscem prowadzenia działalności gospodarczej pod adresem Muzyczna 43b, 02-862 Warszawa, NIP 9512532874, REGON 520948370.</p>
        <p>Treść: To zawartość wypowiedzi Użytkownika zamieszczona w Sklepie, w szczególności informacje w formie tekstu, zdjęcia, grafiki lub innego materiału, które Użytkownik umieścił w obrębie Sklepu.</p>
        <p>Treść nielegalna: To Treść, która sama w sobie lub w odniesieniu do funkcjonalności Sklepu i usług Usługodawcy nie jest zgodna z prawem Unii Europejskiej lub z prawem danego państwa członkowskiego UE, niezależnie od konkretnego przedmiotu lub charakteru tego prawa. Za Treść nielegalną uznaje się w szczególności: obrazy przedstawiające niegodziwe traktowanie dzieci w celach seksualnych; prywatne zdjęcia/grafiki udostępniane bez zgody osoby uprawnionej do danego materiału; cyberstalking; treści służące do sprzedaży produktów niespełniających wymogów lub podrobionych; treści służące do sprzedaży towarów lub świadczenia usług z naruszeniem prawa ochrony konsumentów; treści naruszające prawa autorskie.</p>
        <p>Treść niezgodna z warunkami korzystania z usług Sklepu: To Treść naruszająca i zakłócające zasady funkcjonowania Sklepu, niniejszy Regulamin, a także Treść o charakterze nieprawdziwym, nieaktualnym, naruszającym dobre obyczaje i zasady współżycia społecznego.</p>
        <p>Warunki korzystania z usług Sklepu: To klauzule, niezależnie od ich nazwy lub formy, które regulują stosunek umowny między Usługodawcą a Użytkownikiem.</p>
        <p>Moderacja: To działania niezautomatyzowane lub zautomatyzowane, podejmowane przez Usługodawcę, w szczególności w celu wykrywania, identyfikowania i zwalczania nielegalnych treści lub informacji niezgodnych z warunkami korzystania z usług, przekazywanych przez Użytkowników, w tym wdrażane środki, które wpływają na dostępność, widoczność i osiągalność takich nielegalnych treści lub informacji, takie jak depozycjonowanie takich treści lub informacji, demonetyzacja, uniemożliwienie dostępu do nich lub ich usunięcie, lub które wpływają na możliwość przekazywania takich informacji przez Użytkowników, takie jak zamknięcie lub zawieszenie konta Użytkownika.</p>
        <h2>Ogólne warunki korzystania ze Sklepu</h2>
        <ol>
          <li>Ten Regulamin jest nieodpłatnie udostępniany każdemu Klientowi przed zawarciem umowy w sposób, który umożliwia pozyskanie, odtwarzanie i utrwalenie jego treści za pomocą systemu teleinformatycznego, z którego korzysta Klient.</li>
          <li>Klient ma obowiązek zapoznać się z treścią Regulaminu przed zawarciem umowy. Jeżeli Klient nie akceptuje jego postanowień, nie powinien dokonywać zakupów w Sklepie. Zawarcie Umowy z Usługodawcą oznacza, że Klient zapoznał się z treścią Regulaminu i związany jest z jego postanowieniami.</li>
          <li>Wszystkie ceny Produktów cyfrowych są cenami brutto (razem z podatkiem VAT) w polskich złotych.</li>
          <li>Do poprawnego korzystania ze Sklepu konieczne jest spełnienie Wymagań Technicznych, posiadanie dostępu do urządzenia z Internetem, z aktualnym systemem operacyjnym oraz z aktualną przeglądarką internetową, a także posiadanie konta e-mail. Klient powinien także posiadać wiedzę na temat zagrożeń dotyczących korzystania z Internetu (w tym zakupów online) oraz zabezpieczyć swoje urządzenie w podstawowe środki bezpieczeństwa technicznego (np. programy antywirusowe).</li>
          <li>Klient zobowiązany jest do niedostarczania treści bezprawnych oraz treści zabronionych przez przepisy prawa (np. naruszających dobra osobiste osób trzecich), a także do wprowadzania danych zgodnych ze stanem faktycznym.</li>
          <li>Klient Sklepu zobowiązany jest w szczególności do terminowej zapłaty Ceny i innych ustalonych przez Klienta kosztów w pełnej wysokości.</li>
          <li>Klient nie jest uprawniony do przekazywania loginu i hasła osobom nieuprawnionym lub do korzystania z konta innego Klienta.</li>
          <li>Treści i Usługi cyfrowe mogą być prezentowane w Sklepie w ramach przedsprzedaży lub w Promocji, której warunki zamieszczone są w Sklepie. Cena wskazywana przez Usługodawcę obok Ceny Promocyjnej jest najniższą ceną, w której produkt był dostępny w sklepie w ciągu ostatnich 30 dni (Najniższa cena z ostatnich 30 dni przed obniżką).</li>
          <li>W przypadku udostępnienia Treści i Usługi cyfrowej w ramach Promocji, Usługodawca oznacza, że dana Treść lub Usługa cyfrowa jest w cenie promocyjnej.</li>
          <li>W przypadku udostępnienia Treści i Usługi cyfrowej w ramach przedsprzedaży, Usługodawca oznacza, że dana Treść lub Usługa cyfrowa będzie dostępna w całości w określonym terminie (premiera Produktu). Termin zostanie podany osobom zainteresowanym zakupem w komunikacji e-mail (newsletter) oraz na stronie sprzedażowej.</li>
          <li>W przypadku umożliwienia Klientom zapoznania się z opiniami innych Klientów na stronie Sklepu Usługodawca podejmuje uzasadnione i proporcjonalne kroki, które pozwolą na zweryfikowanie czy opinie są rzetelne i zamieszczone przez osoby, które rzeczywiście korzystały z Treści lub Usługi cyfrowej.</li>
          <li>Jeżeli Cena udostępniona Klientowi na stronie Sklepu jest spersonalizowana, np. ustalona na podstawie informacji o Kliencie uzyskanych z danych marketingowych (profilowanie), Usługodawca udostępnia Klientowi informację na temat indywidualnego dostosowania ceny (personalizacji cen) przy Cenie Treści lub Usługi cyfrowej na stronie Sklepu.</li>
          <li>Usługodawca podejmuje środki organizacyjne i techniczne mające na celu zabezpieczenie bezpieczeństwa korzystania ze Sklepu oraz funkcjonalności dostępnych w ramach strony (formularz rejestracji konta, formularz zamówienia itd.).</li>
        </ol>
        <h2>Usługi elektroniczne na stronie Sklepu, w tym zakładanie Konta Klienta Sklepu</h2>
        <ol>
          <li>Usługodawca świadczy na rzecz Klientów za pośrednictwem Sklepu nieodpłatnie następujące Usługi Elektroniczne: a) Usługę zawierania Umów na zasadach określonych w Regulaminie; b) Usługę Konto Klienta oraz przechowywanie i udostępnianie Klientowi za pośrednictwem Konta historii Zamówień Klienta na stronie Sklepu oraz dostęp do Treści i Usługi cyfrowej za pomocą Konta po zalogowaniu na stronie Sklepu; c) Usługę składania Zamówień na zasadach określonych w Regulaminie; d) Usługę umożliwienia Klientom korzystania z usług Koszyka; e) Usługę udostępnienia Treści i Usług cyfrowych na stronie internetowej Sklepu.</li>
          <li>Klient ma możliwość założenia Konta na stronie internetowej Sklepu przy składaniu Zamówienia. Konto zawiera m.in. informacje o Zamówieniach i pozwala na zapamiętanie użytych wcześniej danych potrzebnych do złożenia Zamówienia.</li>
          <li>Usługodawca świadczy usługę utrzymania Konta w czasie wykonywania Umowy, nie krócej niż w terminie 1 roku od dnia założenia/ostatniego zalogowania Klienta na Konto.</li>
          <li>Korzystanie z Konta możliwe jest po wypełnieniu formularza oraz zaakceptowaniu postanowień niniejszego Regulaminu i kliknięciu przycisku „Załóż konto” lub innego równoznacznego, przy czym Konto zakładane jest automatycznie podczas dokonywania pierwszego zakupu w Sklepie. W przypadku składania Zamówienia poprzez wiadomość e-mail Konto tworzone jest przez Usługodawcę po opłaceniu Ceny, przy czym Klient otrzymuje na wskazany przez siebie adres e-mail wiadomość z linkiem aktywacyjnym oraz samodzielnie ustala hasło do swojego Konta.</li>
          <li>W formularzu zakładania Konta niezbędne jest podanie przez Klienta wskazanych następujących danych: imię i nazwisko, adres poczty elektronicznej, login i hasło.</li>
          <li>Założenie Konta Klienta następuje poprzez wypełnienie formularza rejestracyjnego i przesłanie do Usługodawcy poprzez stronę Sklepu (w ramach składania Zamówienia). Z chwilą przesłania potwierdzenia utworzenia Konta Klienta dochodzi do zawarcia umowy o prowadzenie Konta na stronie Sklepu.</li>
          <li>Umowa o prowadzenie Konta zawierana jest na czas nieokreślony i można wypowiedzieć ją w każdym momencie.</li>
          <li>Klient loguje się na Konto przy użyciu adresu e-mail oraz indywidualnego hasła, które Klient ustala samodzielnie.</li>
          <li>Klient może złożyć Zamówienie poprzez założenie Konta.</li>
          <li>Klient korzystający z platformy easywonders.pl może samodzielnie usunąć swoje Konto w panelu ustawień konta. Usunięcie następuje niezwłocznie i obejmuje trwałe skasowanie danych powiązanych z Kontem. Jeżeli Klient posiada aktywną Subskrypcję, zostaje ona przy tej okazji anulowana i nie zostaną pobrane żadne kolejne opłaty; opłata za rozpoczęty Okres rozliczeniowy nie podlega zwrotowi.</li>
          <li>W pozostałych przypadkach Klient może zgłosić żądanie usunięcia Konta na adres e-mail podany w początkowej części Regulaminu. Konto usuwane jest wówczas w terminie do 30 dni od dnia otrzymania żądania.</li>
          <li>Korzystanie z Koszyka rozpoczyna się z momentem dodania przez Klienta pierwszej Treści lub Usługi cyfrowej do Koszyka.</li>
          <li>Usługa Koszyk świadczona jest nieodpłatnie oraz ma charakter jednorazowy i ulega zakończeniu z chwilą złożenia Zamówienia.</li>
          <li>Reklamacje związane ze świadczeniem Usług Elektronicznych można składać pisemnie na adres siedziby Usługodawcy lub elektronicznie na adres wskazany na początku Regulaminu.</li>
          <li>Ustosunkowanie się do reklamacji przez Usługodawcę następuje niezwłocznie, nie później niż w terminie 14 dni od dnia jej otrzymania.</li>
          <li>W celu przyśpieszenia rozpatrzenia reklamacji rekomenduje się podanie przez Klienta w opisie reklamacji informacji i okoliczności dotyczących przedmiotu reklamacji, w szczególności rodzaju i daty wystąpienia nieprawidłowości oraz żądania Klienta wraz z przekazaniem danych kontaktowych składającego reklamację.</li>
          <li>Podane wyżej wymogi mają formę jedynie rekomendacji Usługodawcy i nie wpływają na skuteczność reklamacji złożonych z pominięciem zalecanego opisu reklamacji.</li>
        </ol>
        <h2>Zawarcie, wykonanie umowy i płatności</h2>
        <ol>
          <li>Usługodawca umożliwia składanie Zamówień oraz zawarcie Umów dotyczących udostępniania Treści i Usług cyfrowych poprzez stronę Sklepu.</li>
          <li>Główne cechy Treści i Usługi cyfrowej oraz specyfikacja są określone na stronie produktowej każdej Treści lub Usługi cyfrowej na stronie Sklepu.</li>
          <li>Zawarcie Umowy pomiędzy Klientem a Usługodawcą może nastąpić po uprzednim złożeniu przez Klienta Zamówienia na zasadach określonych poniżej.</li>
          <li>Umowa zawierana jest po złożeniu Zamówienia na stronie Sklepu za pomocą Formularza Zamówienia, w momencie potwierdzenia jej przez Usługodawcę, przy czym potwierdzenie następuje w formie przesłania wiadomości e-mail przez Usługodawcę na adres e-mail wskazany przez Klienta podczas składania Zamówienia.</li>
          <li>Przedmiotem Umowy jest zobowiązanie Usługodawcy do udostępnienia Treści lub Usług cyfrowych Klientowi za cenę wskazaną na stronie Sklepu płatną przez Klienta.</li>
          <li>Zamówienia można składać 7 dni w tygodniu, 24 godziny na dobę.</li>
          <li>Usługodawca umożliwia Klientowi złożenie Zamówienia w następujący sposób: poprzez dodanie Treści lub Usługi cyfrowej do Koszyka, po czym Klient przechodzi do Formularza zamówienia lub Klient posiadający Konto potwierdza w Formularzu zamówienia aktualność i prawidłowość danych koniecznych do zawarcia i realizacji Umowy.</li>
          <li>Klient, który nie posiada Konta, jest zobowiązany samodzielnie wypełnić Formularz zamówienia w zakresie jego danych niezbędnych do zawarcia i realizacji Umowy.</li>
          <li>W każdym przypadku podanie nieaktualnych lub nieprawdziwych danych Klienta może uniemożliwić realizację Umowy, ponieważ warunkiem złożenia Zamówienia jest prawidłowe i kompletne wypełnienie Formularza zamówienia. W Formularzu zamówienia niezbędne jest podanie przez Klienta następujących danych dotyczących Klienta: imię i nazwisko, dokładny adres, adres poczty elektronicznej oraz danych dotyczących Umowy tj.: wybrana Treść lub Usługa cyfrowa, sposób płatności za Treść i/lub Usługę cyfrową przez Klienta.</li>
          <li>W wypadku Klientów niebędących Konsumentami niezbędne jest także podanie firmy, a jeśli zażądali oni w ramach formularza wystawienia faktury VAT, również danych niezbędnych do wystawienia faktury VAT, w tym NIP.</li>
          <li>Warunkiem złożenia Zamówienia, oprócz wskazanych powyżej okoliczności, jest także zaakceptowanie warunków Regulaminu i Polityki prywatności Usługodawcy, a także zapłata Ceny za Treści i/lub Usługi cyfrowe po wyborze sposobu płatności, który tego wymaga.</li>
          <li>Naciśnięcie przycisku „Zamawiam i płacę” (lub innego o równoznacznym brzmieniu) jest tożsame ze złożeniem Zamówienia (Klient składa ofertę) na wybraną Treść i/lub Usługę cyfrową.</li>
          <li>Klient ma możliwość weryfikacji Treści i Usługi cyfrowej znajdującej się w Koszyku oraz dokonania zmian do czasu złożenia Zamówienia.</li>
          <li>Po kliknięciu przycisku „Zamawiam i płacę” (lub innego o równoznacznym brzmieniu) Klient będzie miał możliwość wyboru operatora płatności i zostanie w sposób automatyczny przekierowany do bramki płatności, obsługiwanej przez wybranego operatora w przypadku wyboru płatności online. Informacje o dostępnych operatorach są na bieżąco podawane na stronie Sklepu. W przypadku Zamówienia składanego na adres e-mail, płatność należy uiścić na rachunek wskazany na fakturze.</li>
          <li>W odpowiedzi na Zamówienie Klient niezwłocznie otrzymuje wiadomość na podany w tym celu adres e-mail z potwierdzeniem otrzymania Zamówienia i rozpoczęcia jego weryfikacji.</li>
          <li>Po zweryfikowaniu Zamówienia, bez nieuzasadnionego opóźnienia, Usługodawca wysyła do Klienta na podany adres e-mail wiadomość z potwierdzeniem przyjęcia oferty, złożonej w ramach przesłania Zamówienia oraz potwierdzeniem rozpoczęcia realizacji Zamówienia lub informację o odmowie przyjęcia wszystkich lub poszczególnych ofert, złożonych w ramach Zamówienia.</li>
          <li>Do zawarcia Umowy dochodzi z chwilą przyjęcia Zamówienia przez Usługodawcę, które następuje w formie przesłania wiadomości e-mail potwierdzającej przyjęcie Zamówienia. W przypadku Zamówienia, które należy opłacić na podstawie faktury wystawionej przez Usługodawcę, Klient jest zobowiązany do zapłaty Ceny w pełnej wysokości, w terminie wskazanym na fakturze wystawionej przez Usługodawcę. W przypadku niedopełnienia tego obowiązku Umowę uważa się za niezawartą.</li>
          <li>W przypadku odmowy przyjęcia oferty bądź ofert złożonych w ramach realizacji Zamówienia przez Klienta, Umowa w zakresie Treści i/lub Usługi cyfrowej, wskazana przez Usługodawcę w wiadomości e-mail z odmową przyjęcia oferty, nie zostaje zawarta. W takim wypadku Usługodawca niezwłocznie, nie później niż w terminie 14 dni od wysłania wiadomości, o której mowa powyżej, zwraca Klientowi uiszczone przez niego płatności, w zakresie w jakim Umowa nie została zawarta.</li>
          <li>Na adres e-mail podany w formularzu przez Klienta Usługodawca wysyła podsumowanie Zamówienia zawierające najważniejsze informacje o Zamówieniu.</li>
          <li>Usługodawca organizuje Promocje na wybrane Treści lub Usługi cyfrowe dostępne na stronie Sklepu. Promocje nie podlegają łączeniu, o ile postanowienia Promocji wyraźnie nie stanowią inaczej. Możliwość skorzystania z danej Promocji może zależeć od dostępności Treści lub Usługi cyfrowej na stronie Sklepu.</li>
          <li>Usługodawca umożliwia następujące metody płatności: a) płatność elektroniczna (realizacja Zamówienia rozpoczęta zostanie po przesłaniu Klientowi przez Usługodawcę potwierdzenia przyjęcia Zamówienia oraz po otrzymaniu przez Usługodawcę informacji o dokonaniu płatności przez Klienta) w formie przelewu tradycyjnego lub płatności dokonanej za pośrednictwem operatora płatności; b) przelew tradycyjny; c) płatność dokonana za pośrednictwem operatora płatności.</li>
          <li>Usługodawca przekaże Klientowi dowód zakupu w formie elektronicznej. Klient wyraża zgodę, aby dowód zapłaty, tj. faktura lub paragon, został sporządzony i przesłany na podany przez niego w trakcie składania Zamówienia, bądź zakładania Konta, adres e-mail.</li>
          <li>Z zastrzeżeniem płatności cyklicznych w ramach Subskrypcji, obsługiwanych przez Stripe, płatność za Treść lub Usługę cyfrową dokonywana jest przy pomocy serwisu PayPro SA (PayPro) z siedzibą w Poznaniu, przy ulicy Pastelowej 8, kod pocztowy 60-198, wpisany do rejestru przedsiębiorców Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy Poznań Nowe Miasto i Wilda, VIII Wydział Gospodarczy Krajowego Rejestru Sądowego pod numerem KRS 0000347935, posiadająca NIP 7792369887, REGON 301345068, o kapitale zakładowym wynoszącym 5 476 300,00 zł, w całości opłaconym, oraz do rejestru krajowych instytucji płatniczych prowadzonego przez Komisję Nadzoru Finansowego pod numerem UKNF IP24/2014.</li>
          <li>Usługodawca nie przechowuje w swojej bazie numerów kart płatniczych Klientów.</li>
          <li>Płatność następuje na zasadach prezentowanych na stronie Sklepu. W razie wątpliwości Klient może skontaktować się z Usługodawcą, kierując wiadomość na adres wskazany w Regulaminie.</li>
        </ol>
        <h2>Subskrypcja i płatności cykliczne</h2>
        <ol>
          <li>Usługodawca umożliwia Klientowi zakup dostępu do wybranych Treści i Usług cyfrowych w modelu Subskrypcji, z odnawialną płatnością cykliczną.</li>
          <li>Subskrypcja dostępna jest w wariantach wskazanych na stronie Sklepu, w szczególności w wariancie miesięcznym lub rocznym. Cena oraz długość Okresu rozliczeniowego każdego wariantu są podane na stronie Sklepu przed złożeniem Zamówienia.</li>
          <li>Zawierając Umowę Subskrypcji, Klient wyraża zgodę na cykliczne, automatyczne pobieranie Ceny za kolejne Okresy rozliczeniowe za pośrednictwem operatora płatności, do czasu rezygnacji z Subskrypcji.</li>
          <li>Subskrypcja rozpoczyna się bezpłatnym okresem próbnym trwającym 7 dni, liczonym od dnia zawarcia Umowy Subskrypcji. W okresie próbnym Klient korzysta z pełnego dostępu i nie ponosi żadnej opłaty. Pierwsza opłata pobierana jest automatycznie po zakończeniu okresu próbnego, chyba że Klient zrezygnuje z Subskrypcji przed jego upływem. Opłata za każdy kolejny Okres rozliczeniowy pobierana jest automatycznie na początku tego okresu, z wykorzystaniem metody płatności wskazanej przez Klienta.</li>
          <li>Rezygnacja z Subskrypcji w trakcie okresu próbnego powoduje, że żadna opłata nie zostanie pobrana.</li>
          <li>Subskrypcja odnawia się automatycznie na kolejny Okres rozliczeniowy, o ile Klient nie zrezygnuje z niej zgodnie z postanowieniami poniższymi.</li>
          <li>Klient może w każdej chwili zrezygnować z Subskrypcji, bez podawania przyczyny. Rezygnacji dokonuje się poprzez panel zarządzania Subskrypcją dostępny po zalogowaniu lub poprzez kontakt z Usługodawcą na adres e-mail wskazany w Regulaminie.</li>
          <li>Rezygnacja z Subskrypcji powoduje, że nie zostanie pobrana opłata za kolejny Okres rozliczeniowy. Klient zachowuje dostęp do Treści i Usług cyfrowych objętych Subskrypcją do końca opłaconego Okresu rozliczeniowego, w którym dokonał rezygnacji. Po jego zakończeniu dostęp wygasa.</li>
          <li>Usługodawca nie zwraca opłaty za bieżący, rozpoczęty Okres rozliczeniowy w przypadku rezygnacji z Subskrypcji w jego trakcie, z zastrzeżeniem bezwzględnie obowiązujących przepisów o prawach konsumenta oraz postanowień o niezgodności z Umową. Postanowienie to nie ogranicza prawa odstąpienia od Umowy Subskrypcji w terminie 14 dni od jej zawarcia, opisanego w sekcji „Odstąpienie od umowy”.</li>
          <li>W przypadku nieudanego pobrania opłaty za kolejny Okres rozliczeniowy (np. z powodu braku środków lub wygaśnięcia karty), Usługodawca podejmuje kolejne próby pobrania opłaty przez okres do dwóch tygodni. W tym czasie dostęp Klienta do Treści i Usług cyfrowych pozostaje aktywny, a Klient otrzymuje na adres e-mail przypisany do Konta informację o nieudanej płatności wraz z możliwością aktualizacji metody płatności. Jeżeli żadna z prób nie zakończy się powodzeniem, Subskrypcja zostaje zakończona, a dostęp do Treści i Usług cyfrowych objętych Subskrypcją wygasa.</li>
          <li>Usługodawca może zmienić Cenę Subskrypcji. O zmianie Ceny Klient zostanie poinformowany z wyprzedzeniem na adres e-mail przypisany do Konta. Zmiana Ceny obowiązuje od kolejnego Okresu rozliczeniowego następującego po poinformowaniu Klienta. Jeżeli Klient nie akceptuje nowej Ceny, może zrezygnować z Subskrypcji przed rozpoczęciem kolejnego Okresu rozliczeniowego.</li>
          <li>Płatności cykliczne w ramach Subskrypcji obsługiwane są przez operatora płatności Stripe Payments Europe, Limited (Stripe). Usługodawca nie przechowuje danych karty płatniczej Klienta — dane te przetwarzane są przez operatora płatności.</li>
          <li>Klient może zmienić wariant Subskrypcji (np. z miesięcznego na roczny) w panelu zarządzania Subskrypcją dostępnym po zalogowaniu. Zmiana obowiązuje na zasadach wskazanych w panelu w chwili jej dokonania. W przypadku Konta Lektora zmiana liczby wykupionych miejsc następuje po kontakcie z Usługodawcą na adres e-mail podany w Regulaminie.</li>
        </ol>
        <h2>Konto lektora i dostęp dla uczniów</h2>
        <ol>
          <li>Konto Lektora jest szczególnym rodzajem Subskrypcji, w ramach której Klient (Lektor) uzyskuje dostęp do Treści i Usług cyfrowych oraz możliwość przypisania dostępu określonej liczbie Uczniów.</li>
          <li>Liczba miejsc (dostępów dla Uczniów) zależy od wybranego przez Lektora wariantu Subskrypcji i jest wskazana na stronie Sklepu. Cena Subskrypcji uzależniona jest od liczby wykupionych miejsc.</li>
          <li>Lektor przypisuje dostęp Uczniom poprzez wskazanie w panelu ich adresów e-mail. Liczba przypisanych Uczniów nie może przekroczyć liczby wykupionych miejsc.</li>
          <li>Stroną Umowy Subskrypcji jest wyłącznie Lektor. To Lektor zobowiązany jest do zapłaty Ceny za całą Subskrypcję, niezależnie od liczby faktycznie korzystających Uczniów. Uczniowie nie są stroną Umowy i nie ponoszą wobec Usługodawcy opłat z tytułu dostępu przyznanego przez Lektora.</li>
          <li>Dostęp Ucznia do Treści i Usług cyfrowych jest pochodną Subskrypcji Lektora i obowiązuje wyłącznie w okresie jej trwania. W przypadku rezygnacji Lektora z Subskrypcji, jej wygaśnięcia, zawieszenia z powodu nieopłacenia lub usunięcia Ucznia przez Lektora, dostęp danego Ucznia wygasa.</li>
          <li>Lektor oświadcza, że posiada podstawę do przekazania Usługodawcy adresów e-mail Uczniów w celu przypisania im dostępu oraz że poinformował Uczniów o przekazaniu ich danych w tym celu. Zasady przetwarzania danych osobowych Uczniów określa Polityka prywatności.</li>
          <li>Lektor ponosi odpowiedzialność za korzystanie z przypisanych miejsc zgodnie z Regulaminem, w szczególności za to, by dostęp nie był udostępniany osobom innym niż wskazani przez niego Uczniowie.</li>
        </ol>
        <h2>Treści cyfrowe i usługi cyfrowe</h2>
        <ol>
          <li>Treści i Usługi cyfrowe oferowane na stronie Sklepu dotyczą treści o charakterze edukacyjnym. W ramach Umowy zawartej zgodnie z postanowieniami niniejszego Regulaminu Usługodawca udostępnia Klientowi Treści cyfrowe i/lub Usługi cyfrowe zgodnie z Zamówieniem Klienta.</li>
          <li>Realizacja Zamówienia oznacza, że Usługodawca dostarcza Klientowi dane umożliwiające dostęp do treści zgodnych z Zamówieniem Klienta. Dane dostępowe przesyłane są na adres e-mail wskazany podczas składania Zamówienia (login i hasło do Konta Klienta na stronie Sklepu). Utworzenie Konta Klienta na stronie Sklepu, które umożliwia korzystanie z Treści i/lub Usług cyfrowych, jest nieodpłatne.</li>
          <li>Ceny Treści i Usług cyfrowych prezentowane są Klientowi na stronie internetowej Sklepu oraz w trakcie składania Zamówienia. Wszystkie ceny podane na stronach Sklepu są cenami brutto uwzględniającymi podatki.</li>
          <li>Ze względu na rodzaj i czas trwania Usług lub Treści cyfrowych poszczególne warianty Treści lub Usług cyfrowych mogą różnić się swoim zakresem oraz poziomem dostępów do materiałów.</li>
          <li>Wszystkie Usługi i Treści cyfrowe prezentowane są na stronie Sklepu. Dostęp do zawartości Zamówienia zostanie przyznany Klientowi niezwłocznie po zawarciu Umowy (zazwyczaj po wniesieniu na rzecz Usługodawcy przez Klienta opłaty odpowiadającej Cenie wybranej Treści lub Usłudze cyfrowej), o ile inaczej nie wskazano w opisie Treści lub Usługi cyfrowej. Konto Klienta oznacza indywidualny dla każdego Klienta panel, uruchomiony dla niego przez Usługodawcę na stronie Sklepu.</li>
          <li>Z chwilą zalogowania się do Konta Klienta po zakupie Usługi lub Treści cyfrowej lub z chwilą uzyskania dostępu do zamówionej Treści lub Usługi cyfrowej, w szczególności poprzez przesłanie linku do ściągnięcia materiałów lub uzyskania do nich dostępu, przedmiot Umowy uważa się za dostarczony w całości Klientowi.</li>
          <li>Jeżeli w opisie Treści lub Usługi cyfrowej Usługodawca określił inny termin dostarczenia Treści lub Usługi cyfrowej, to Klienta obowiązuje termin wskazany przez Usługodawcę na stronie Sklepu (przedsprzedaż).</li>
        </ol>
        <h2>Prawa autorskie</h2>
        <ol>
          <li>Klient zobowiązany jest do przestrzegania warunków niniejszej licencji w zakresie treści dostępnych w ramach Sklepu oraz poszczególnych Treści i Usług cyfrowych. Usługodawca może określić warunki licencji odrębnie, zamieszczając stosowny zapis w opisie Treści lub Usługi cyfrowej.</li>
          <li>Klient ma prawo korzystać z Treści lub Usługi cyfrowej wyłącznie na własny użytek, o ile inaczej nie wskazano w opisie Produktu. Dozwolone jest wydrukowanie Produktu (np. ebooka lub workbooka) w liczbie kopii niezbędnej do własnego użytku Klienta, bez prawa ich dalszego rozpowszechniania.</li>
          <li>Zabrania się Klientowi udostępniać Treści cyfrowe lub dane do swojego Konta Klienta innym podmiotom, z wyjątkiem dostępu przyznawanego Uczniom przez Lektora w ramach Konta Lektora, na zasadach określonych w Regulaminie.</li>
          <li>Dostępne w ramach Sklepu Treści i Usługi cyfrowe nie mogą być przedmiotem rozporządzenia przez Klienta (w szczególności odsprzedaży czy dystrybucji i sprzedaży handlowej).</li>
          <li>Licencja udzielona Klientowi nie obejmuje prawa do: a) trwałego lub czasowego zwielokrotnienia treści dostępnych w ramach Sklepu, w tym Produktów, w całości lub w części, w celu innym niż utworzenie kopii na własny użytek; b) wprowadzania jakichkolwiek innych zmian w części lub w całości treści, w tym Produktów, dostępnych na stronie Sklepu, z zastrzeżeniem, że w przypadku Produktów typu workbook (zeszyt ćwiczeń) Klient ma prawo wypełniać przeznaczone do tego pola w ramach własnej nauki; c) odpłatnego rozpowszechniania treści, w tym Produktów, dostępnych na stronie Sklepu jakimikolwiek środkami i w jakiejkolwiek formie; d) nieodpłatnego rozpowszechniania treści, w tym Produktów, dostępnych na stronie Sklepu jakimikolwiek środkami i w jakiejkolwiek formie.</li>
          <li>O ile w opisie Treści lub Usługi cyfrowej nie wskazano inaczej, licencja udzielana jest na czas trwania Umowy – 365 dni. W przypadku Subskrypcji licencja obowiązuje przez czas trwania Subskrypcji i wygasa wraz z utratą dostępu do Treści i Usług cyfrowych objętych Subskrypcją.</li>
        </ol>
        <h2>Uprawnienia w razie niezgodności z umową</h2>
        <ol>
          <li>Usługodawca ponosi odpowiedzialność wobec Klienta, jeżeli Treść cyfrowa lub Usługa cyfrowa są niezgodne z umową. Szczegóły dotyczące niezgodności Usługi lub Treści cyfrowej z umową regulują przepisy Kodeksu cywilnego w odniesieniu do Przedsiębiorców oraz Ustawy z dnia 30 maja 2014 r. o prawach konsumenta, w odniesieniu do Konsumentów oraz Przedsiębiorców na prawach konsumenta. Dla uniknięcia wątpliwości wskazuje się, że uprawnienia z tytułu niezgodności Treści cyfrowej lub Usługi cyfrowej z umową dotyczą klientów Sklepu będących Konsumentami i Przedsiębiorcami na prawach konsumenta.</li>
          <li>W przypadku stwierdzenia niezgodności Treści lub Usługi cyfrowej z Umową Klient powinien skontaktować się z Usługodawcą (na adres e-mail podany na początku Regulaminu lub listownie), określając jednocześnie swoje roszczenie związane z niezgodnością Treści lub Usługi cyfrowej z Umową.</li>
          <li>Jeżeli Treść cyfrowa lub Usługa cyfrowa są niezgodne z Umową, Konsument może żądać doprowadzenia do zgodności z Umową.</li>
          <li>Usługodawca może odmówić doprowadzenia do zgodności z Umową, jeżeli doprowadzenie do zgodności Treści cyfrowej lub Usługi cyfrowej z Umową w sposób wybrany przez Konsumenta jest niemożliwe lub wymagałoby poniesienia nadmiernych kosztów dla Usługodawcy.</li>
          <li>Przy ocenie nadmierności kosztów uwzględnia się wszelkie okoliczności sprawy, w szczególności znaczenie braku zgodności Treści lub Usługi cyfrowej z Umową oraz wartość Treści lub Usługi cyfrowej zgodnych z Umową.</li>
          <li>Usługodawca doprowadza Treść lub Usługę cyfrową do zgodności z Umową w rozsądnym terminie od chwili, w której Usługodawca został poinformowany przez Konsumenta o braku zgodności z Umową, bez nadmiernych niedogodności dla Konsumenta, uwzględniając ich charakter oraz cel, w jakim są wykorzystywane. Koszty doprowadzenia Treści cyfrowej lub Usługi cyfrowej do zgodności z Umową ponosi Usługodawca.</li>
          <li>Jeżeli Treść lub Usługa cyfrowa są niezgodne z Umową, Konsument może złożyć oświadczenie o obniżeniu ceny albo odstąpieniu od Umowy, gdy: a) doprowadzenie do zgodności z Umową jest niemożliwe albo wymaga nadmiernych kosztów, zgodnie z punktem 4 i 5; b) Usługodawca nie doprowadził Treści cyfrowej lub usługi cyfrowej do zgodności z Umową zgodnie z punktem 6; c) brak zgodności z Umową występuje nadal, mimo że Usługodawca próbował doprowadzić Treść cyfrową lub Usługę cyfrową do zgodności z Umową; d) z oświadczenia Usługodawcy lub z okoliczności wyraźnie wynika, że nie doprowadzi on Treści lub Usługi cyfrowej do zgodności z Umową w rozsądnym czasie lub bez nadmiernych niedogodności dla Konsumenta.</li>
          <li>Usługodawca rozpatrzy reklamację w rozsądnym terminie 14 dni.</li>
          <li>Jeżeli Klient będący Konsumentem, wykonując uprawnienia z tytułu niezgodności Produktu z Umową, wystosował odpowiednie żądania do Usługodawcy, a Usługodawca nie ustosunkował się do tego żądania w terminie 14 dni kalendarzowych, uważa się, że żądanie to uznał za uzasadnione.</li>
          <li>W celu przyśpieszenia rozpatrzenia reklamacji w zgłoszeniu reklamacyjnym rekomenduje się podanie przez Klienta w opisie reklamacji informacji i okoliczności dotyczących przedmiotu reklamacji, w szczególności rodzaju i daty wystąpienia niezgodności z umową oraz danych kontaktowych składającego reklamację. Rekomendacje podane w zdaniu poprzednim mają formę jedynie zalecenia i nie wpływają na skuteczność reklamacji złożonych z pominięciem zalecanego opisu reklamacji.</li>
          <li>Jeżeli Klient jest Przedsiębiorcą, odpowiedzialność Usługodawcy z tytułu rękojmi jest wyłączona na podstawie z art. 558 § 1 ustawy Kodeks cywilny.</li>
          <li>Więcej informacji na temat praw kupujących można znaleźć na stronie Urzędu Ochrony Konkurencji i Konsumenta – https://prawakonsumenta.uokik.gov.pl.</li>
          <li>Usługodawca odpowiada za brak zgodności z umową Treści lub Usługi cyfrowej, dostarczanych jednorazowo lub w częściach, który istniał w chwili jej dostarczenia i ujawnił się w ciągu dwóch lat od tej chwili. Domniemywa się, że brak zgodności z Umową, który ujawnił się przed upływem roku od dostarczenia Treści lub Usługi cyfrowej, istniał w chwili jej dostarczenia.</li>
          <li>Usługodawca nie może powoływać się na upływ terminu do stwierdzenia braku zgodności Treści lub Usługi cyfrowej z Umową, który jest wskazany w punkcie 13, jeżeli ten brak podstępnie zataił.</li>
          <li>Usługodawca odpowiada za brak zgodności z Umową Treści cyfrowej lub Usługi cyfrowej dostarczanych w sposób ciągły, który wystąpił lub ujawnił się w czasie, w którym zgodnie z Umową miały być dostarczane. Domniemywa się, że brak zgodności z Umową wystąpił w tym czasie, jeżeli w tym czasie się ujawnił.</li>
          <li>Domniemania wskazane w punktach 13 i 15 nie mają zastosowania, jeżeli: a) środowisko cyfrowe Konsumenta nie jest kompatybilne z wymaganiami technicznymi, o których Usługodawca poinformował go w sposób jasny i zrozumiały przed zawarciem Umowy; b) Konsument, poinformowany w jasny i zrozumiały sposób przed zawarciem Umowy o obowiązku współpracy z Usługodawcą, w rozsądnym zakresie i przy zastosowaniu najmniej uciążliwych dla siebie środków technicznych, w celu ustalenia czy brak zgodności Treści cyfrowej lub Usługi cyfrowej z Umową wynika z cech środowiska cyfrowego Konsumenta, nie wykonuje tego obowiązku w odpowiednim czasie.</li>
          <li>Uprawnienia z tytułu niezgodności Usługi lub Treści cyfrowej z Umową dotyczą Klientów Sklepu będących Konsumentami lub Przedsiębiorcami na prawach konsumenta.</li>
          <li>Przedsiębiorca na prawach konsumenta akceptuje niniejszy Regulamin, a następnie korzysta ze swoich uprawnień. Przedsiębiorca na prawach konsumenta powinien uzupełnić stosowny formularz niezgodności Produktu z umową, a w szczególności dane poświadczające okoliczności potwierdzające jego status zgodny z art. 7aa ustawy o prawach konsumenta lub przekazać te informacje w inny sposób Usługodawcy.</li>
          <li>Przedsiębiorca na prawach konsumenta oświadcza w formularzu przesłanym do Usługodawcy, że zawarta Umowa jest bezpośrednio związana z prowadzoną przez niego działalnością gospodarczą, ale nie posiada dla niego charakteru zawodowego, wynikającego w szczególności z przedmiotu wykonywanej działalności gospodarczej.</li>
        </ol>
        <h2>Odstąpienie od umowy</h2>
        <ol>
          <li>Jeśli w toku zakupu Konsument lub Przedsiębiorca na prawach konsumenta wyraził zgodę na wykonanie Umowy i dostarczenie mu Treści lub Usługi cyfrowej przed upływem terminu do odstąpienia od Umowy, traci on prawo do odstąpienia od Umowy zawartej z Usługodawcą.</li>
          <li>Jeżeli Umowa dotyczy świadczenia Usług Elektronicznych, a Usługodawca wykonał w pełni Usługę Elektroniczną za wyraźną zgodą Konsumenta lub Przedsiębiorcy na prawach Konsumenta, który został poinformowany przed rozpoczęciem świadczenia, że po spełnieniu świadczenia traci prawo do odstąpienia, wówczas prawo do odstąpienia nie będzie mu przysługiwać.</li>
          <li>W sytuacji, gdy nie występują okoliczności wskazane powyżej (punkty 1 i 2), Konsument lub Przedsiębiorca na prawach konsumenta ma prawo odstąpić od Umowy bez podawania przyczyny w terminie 14 dni od dnia zawarcia Umowy.</li>
          <li>Klientowi nie przysługuje prawo do odstąpienia od Umowy bez podania przyczyn, o ile zostały spełnione warunki przewidziane w ust. 1 lub w ust. 2. Działanie Sklepu opiera się na dostarczaniu Klientowi Treści lub Usług cyfrowych. W związku z tym rozpoczęcie korzystania z Treści lub Usługi cyfrowej przed upływem 14 dni od dnia dokonania zakupu powoduje utratę prawa odstąpienia od Umowy.</li>
          <li>Odstąpienie od Umowy następuje poprzez poinformowanie Usługodawcy o swojej decyzji poprzez złożenie oświadczenia. Takie oświadczenie może zostać wysłane pocztą tradycyjną lub pocztą elektroniczną. Klient może skorzystać ze wzoru formularza reklamacyjnego, dostępnego poniżej regulaminu, jednak nie jest to obowiązkowe.</li>
          <li>W celu zachowania terminu odstąpienia od Umowy wystarczające jest, aby Konsument lub Przedsiębiorca na prawach konsumenta wysłał informację dotyczącą wykonania przysługującego mu prawa odstąpienia od umowy przed upływem wskazanego terminu odstąpienia od umowy.</li>
          <li>W przypadku odstąpienia od umowy Usługodawca zwraca Konsumentowi lub Przedsiębiorcy na prawach konsumenta wszystkie otrzymane od niego płatności.</li>
          <li>Zwrot płatności zostanie dokonany przy użyciu takich samych sposobów płatności, jakie zostały przez Konsumenta lub Przedsiębiorcę na prawach konsumenta użyte w pierwotnej transakcji, chyba że Konsument lub Przedsiębiorca na prawach konsumenta wyraźnie wskazał na inne rozwiązanie.</li>
          <li>Konsument lub Przedsiębiorca na prawach konsumenta nie poniesie żadnych opłat w związku z formą zwrotu płatności.</li>
          <li>Postanowienia punktów 1–4 dotyczą jednorazowych Treści i Usług cyfrowych. Do Umowy Subskrypcji stosuje się punkty 11–14 poniżej.</li>
          <li>Konsumentowi oraz Przedsiębiorcy na prawach konsumenta przysługuje prawo odstąpienia od Umowy Subskrypcji bez podawania przyczyny w terminie 14 dni od dnia jej zawarcia.</li>
          <li>Zawierając Umowę Subskrypcji, Klient żąda rozpoczęcia świadczenia usługi przed upływem terminu do odstąpienia od Umowy — dostęp do Treści i Usług cyfrowych przyznawany jest niezwłocznie, wraz z rozpoczęciem bezpłatnego okresu próbnego.</li>
          <li>Odstąpienie od Umowy Subskrypcji w trakcie bezpłatnego okresu próbnego nie wiąże się z żadnymi kosztami po stronie Klienta, ponieważ w tym okresie żadna opłata nie jest pobierana.</li>
          <li>W przypadku odstąpienia od Umowy Subskrypcji po zakończeniu okresu próbnego i pobraniu opłaty, Usługodawca zwraca pobraną Cenę pomniejszoną o kwotę proporcjonalną do zakresu świadczenia spełnionego do chwili odstąpienia, liczoną za dni faktycznego dostępu po zakończeniu okresu próbnego. Zwrot następuje niezwłocznie, nie później niż w terminie 14 dni od otrzymania oświadczenia o odstąpieniu, przy użyciu tego samego sposobu płatności.</li>
        </ol>
        <h2>Publikowanie treści, moderacja i ograniczenia publikowania treści</h2>
        <ol>
          <li>Jeśli w ramach funkcjonowania Sklepu Usługodawca stwarza możliwość pozostawienia Treści przez Użytkownika, to Usługodawca przechowuje ją zgodnie z niniejszym Regulaminem.</li>
          <li>Usługodawca podejmuje bezzwłocznie odpowiednie działania w celu usunięcia lub uniemożliwienia dostępu do Treści nielegalnych, gdy uzyska taką wiedzę lub wiadomość.</li>
          <li>Usługodawca w ramach Sklepu może dokonać moderacji Treści umieszczanych przez Użytkowników z należytą starannością, obiektywnie i proporcjonalnie oraz z należytym uwzględnieniem praw i prawnie uzasadnionych interesów wszystkich zaangażowanych stron.</li>
          <li>Usługodawca nie używa narzędzi służących do automatycznego moderowania treści.</li>
          <li>O moderacji Treści Usługodawca informuje Użytkownika, który daną treść umieścił, o ile Usługodawca dysponuje danymi umożliwiającymi skontaktowanie się z danym Użytkownikiem wraz z podaniem uzasadnienia.</li>
          <li>W uzasadnieniu o podjęciu moderacji Treści Usługodawca wskazuje konkretne podstawy do zastosowania użytej sankcji.</li>
          <li>W przypadku powzięcia informacji o Treści niezgodnej z warunkami korzystania z usług Sklepu Usługodawca może wezwać Użytkownika do samodzielnego jej zmoderowania.</li>
          <li>Użytkownik zobowiązany jest do niedostarczania Treści bezprawnych, nielegalnych, zabronionych przez przepisy prawa (np. naruszających dobra osobiste osób trzecich), wprowadzania danych zgodnych ze stanem faktycznym oraz Treści niezgodnych z warunkami korzystania z usług Sklepu.</li>
          <li>Użytkownik zobowiązany jest w szczególności do: a) podawania w udostępnionych przez Sklep formularzach wyłącznie prawdziwych, aktualnych i niezbędnych danych oraz niezwłocznego aktualizowania danych, w tym danych osobowych, podanych przez Użytkownika w związku z zawarciem Umów; b) korzystania z usług i funkcjonalności udostępnianych przez Sklep w sposób niezakłócający funkcjonowania Sklepu oraz w sposób zgodny z przepisami obowiązującego prawa, postanowieniami Regulaminu, a także zgodnie ze zwyczajami i zasadami współżycia społecznego, także w sposób niezakłócający funkcjonowania pozostałych Użytkowników Sklepu; c) niedostarczania i nieprzekazywania w ramach Sklepu jakichkolwiek treści zabronionych przez przepisy obowiązującego prawa, w szczególności naruszających majątkowe prawa autorskie osób trzecich lub ich dobra osobiste; d) nieumieszczania treści o charakterze bezprawnym, takich jak: rozsyłanie lub umieszczanie w Sklepie niezamówionej informacji handlowej (spam) lub umieszczanie jakichkolwiek treści naruszających przepisy prawa; e) niemodyfikowania w sposób nieuprawniony treści dostarczanych przez Sklep; f) niepodejmowania czynności mających na celu wejście w posiadanie informacji nieprzeznaczonych dla Użytkownika.</li>
          <li>Usługodawca nie ma obowiązku monitorowania Treści, które Użytkownicy przekazują lub przechowują w ramach Sklepu, ani aktywnego ustalania faktów lub okoliczności wskazujących na nielegalną działalność.</li>
        </ol>
        <h2>Zgłaszanie Treści nielegalnych oraz niezgodnych z warunkami korzystania z usług Sklepu</h2>
        <ol>
          <li>Usługodawca stosuje procedury, które umożliwiają dowolnej osobie zgłoszenie Treści, które dana osoba lub dany podmiot uważają za nielegalne oraz niezgodne z warunkami korzystania z usług Sklepu.</li>
          <li>Zgłoszenie może nastąpić drogą elektroniczną na wskazany na początku tego Regulaminu adres e-mail.</li>
          <li>Zgłoszenie powinno zawierać: a. lokalizację Treści w Sklepie w postaci bezpośredniego linku do Treści; b. przyczyny uznania lub uzasadnionego podejrzenia uznania tej Treści za nielegalną lub niezgodną z warunkami korzystania z usług Sklepu; c. dane kontaktowe osoby zgłaszającej, w tym imię, nazwisko lub nazwę, adres e-mail, chyba że zgłoszenie dotyczy przestępstwa związanego z niegodziwym traktowaniem lub wykorzystaniem w celach seksualnych, pornografią dziecięcą, nagabywania dzieci do celów seksualnych oraz podżegania, pomocnictwa i usiłowania w zakresie tych przestępstw; d. oświadczenie, że osoba zgłaszająca powzięła w dobrej wierze przekonanie, że zgłaszane Treści są nielegalne lub niezgodne z warunkami korzystania z usług Sklepu, w szczególności, że stawiane zarzuty są prawdziwe i kompletne.</li>
          <li>Usługodawca niezwłocznie, nie później niż 14 dni roboczych, potwierdza osobie zgłaszającej otrzymanie zgłoszenia, jeśli w zgłoszeniu został wskazany jej adres e-mail.</li>
          <li>Zgłoszenie jest uznawane przez Usługodawcę za prawdziwe, jeśli Usługodawca bez szczegółowej analizy prawnej stwierdzi nielegalność lub niezgodność Treści.</li>
          <li>Usługodawca informuje niezwłocznie osobę zgłaszającą oraz inne osoby zainteresowane sprawą, nie później niż 14 dni od otrzymania zgłoszenia, o powziętej decyzji dotyczącej zgłoszenia, informując o możliwości odwołania się od decyzji.</li>
          <li>Przed wydaniem decyzji Usługodawca może zwrócić się do Użytkownika, który umieścił Treści objęte zgłoszeniem o udzielenie wyjaśnień do zgłoszenia, jeśli jest to niezbędne do podjęcia decyzji.</li>
          <li>Usługodawca rozpatruje wszystkie zgłoszenia oraz podejmuje decyzje w odniesieniu do Treści, których dotyczą zgłoszenia, w sposób terminowy, obiektywny i niearbitralny, oraz z zachowaniem należytej staranności.</li>
          <li>Usługodawca nie używa narzędzi służących do automatycznego rozpatrywania zgłoszeń.</li>
        </ol>
        <h2>Procedura odwoławcza od zgłoszenia Treści nielegalnych lub niezgodnych z warunkami korzystania z usług Sklepu</h2>
        <ol>
          <li>Od decyzji Usługodawcy wydanej w sprawie zgłoszenia funkcjonowania w Sklepie Treści nielegalnej lub niezgodnej z warunkami korzystania z usług Sklepu przysługuje odwołanie.</li>
          <li>Odwołanie można złożyć w formie elektronicznej nie później niż 14 dni od dnia otrzymania decyzji.</li>
          <li>Odwołanie powinno zawierać w szczególności: a. precyzyjne wskazania, dlaczego wydana decyzja jest nieprawidłowa; b. uzasadnienie stanowiska; c. wskazanie negatywnych skutków wydania decyzji dla osoby zgłaszającej lub osoby trzeciej.</li>
          <li>Usługodawca rozpatrzy odwołanie nie później niż 14 dni od jego otrzymania. O wydanej decyzji na skutek odwołania Usługodawca poinformuje osobę zgłaszającą i inne osoby zainteresowane wynikiem sprawy.</li>
          <li>Decyzja wydana w sprawie po rozpatrzeniu odwołania ma charakter ostateczny i nie przysługuje od niej kolejne odwołanie do Usługodawcy.</li>
        </ol>
        <h2>Sankcje za publikowanie Treści nielegalnej lub niezgodnej z warunkami korzystania z usług Sklepu</h2>
        <ol>
          <li>Usługodawca ma możliwość zastosowania sankcji wobec Użytkownika, który umieścił w ramach Sklepu Treści nielegalne lub Treści niezgodne z warunkami korzystania z usług Sklepu, również na skutek wydania decyzji o dokonaniu przez Użytkownika takiego naruszenia na podstawie rozpatrzonego zgłoszenia.</li>
          <li>Usługodawca ma możliwość: a. ograniczyć widoczność Treści, w tym dokonać jej usunięcia, uniemożliwić do niej dostęp lub ją depozycjonować; b. zawiesić, zakończyć lub w inny sposób ograniczyć płatności pieniężne dla Użytkownika, który daną Treść w ramach Sklepu umieścił; c. zawiesić lub zakończyć świadczenie usługi w całości lub w części dla Użytkownika, który dopuścił się naruszenia; d. zawiesić lub zamknąć konto Użytkownika, który dopuścił się naruszenia.</li>
          <li>W przypadku, gdy Usługodawca poweźmie jakiekolwiek informacje, dające podstawę do podejrzenia, że popełniono, popełnia się lub może dojść do popełnienia przestępstwa zagrażającego życiu lub bezpieczeństwu osoby lub osób, natychmiast informuje o swoim podejrzeniu właściwe organy ścigania lub organy sądowe.</li>
        </ol>
        <h2>Pozasądowe sposoby rozwiązywania sporów, rozpatrywania reklamacji i dochodzenia roszczeń dla konsumentów</h2>
        <ol>
          <li>Usługodawca wyraża zgodę na poddanie ewentualnych sporów wynikłych w związku z zawartymi Umowami na drodze postępowania polubownego, mediacyjnego. Szczegóły zostaną określone przez strony konfliktu.</li>
          <li>Wszelkie spory związane z usługami świadczonymi przez Usługodawcę będą rozstrzygane przez sądy powszechne, a prawem właściwym jest prawo polskie.</li>
          <li>Klient będący Konsumentem ma możliwość skorzystania z pozasądowego sposobu rozpatrywania reklamacji i dochodzenia roszczeń. Zasady dostępu do tych procedur dostępne są w siedzibach oraz na stronach internetowych powiatowych (miejskich) rzeczników konsumentów, organizacji społecznych, do których zadań statutowych należy ochrona konsumentów, a także wojewódzkich inspektoratów inspekcji handlowej oraz pod następującymi adresami internetowymi Urzędu Ochrony Konkurencji i Konsumentów: http://www.uokik.gov.pl/spory_konsumenckie.php; http://www.uokik.gov.pl/sprawy_indywidualne.php; http://www.uokik.gov.pl/wazne_adresy.php.</li>
          <li>Istnieje również możliwość skorzystania z platformy internetowego systemu rozstrzygania sporów pomiędzy konsumentami a przedsiębiorcami na szczeblu unijnym (platforma ODR), która dostępna jest pod adresem: http://ec.europa.eu/consumers/odr.</li>
          <li>Postanowienia Regulaminu nie udaremniają możliwości powoływania się przez Klientów na bezwzględnie obowiązujące przepisy prawa regulujące ochronę praw konsumentów.</li>
        </ol>
        <h2>Obowiązywanie i zmiany w regulaminie</h2>
        <ol>
          <li>Usługodawca może wprowadzać zmiany w tym Regulaminie z ważnych przyczyn, także jeżeli zmienią się warunki zawarcia Umowy, przy zmianie obowiązujących przepisów, przy wprowadzeniu nowych Treści lub Usług cyfrowych, a także przy zmianie rozwiązań informatycznych.</li>
          <li>Klienci, którzy posiadają Konto na stronie Sklepu, o każdej zmianie Regulaminu zostaną powiadomieni pocztą elektroniczną na adres e-mail przypisany do Konta Klienta.</li>
          <li>W odniesieniu do Klientów niebędących Konsumentami Usługodawca może dokonać zmiany Regulaminu w każdym czasie na podstawie powszechnie obowiązujących przepisów prawa.</li>
          <li>Do umów zawartych przed zmianą Regulaminu stosuje się Regulamin obowiązujący w dacie zawarcia umowy. Zmiana Regulaminu jest skuteczna w terminie 14 dni od dnia opublikowania.</li>
          <li>Regulamin podlega prawu polskiemu.</li>
          <li>Czynności związane z Regulaminem dokonywane przez Klientów niebędących Konsumentami powinny być dokonywane w formie dokumentowej. Wszelkie spory pomiędzy Usługodawcą a Klientami niebędącymi konsumentami rozstrzygane będą przez sąd właściwy dla siedziby lub miejsca zamieszkania Usługodawcy.</li>
          <li>Usługodawca może rozwiązać Umowę o Świadczenie Usług z Klientem za 30-dniowym okresem wypowiedzenia z ważnych przyczyn, rozumianych jako zmiana przepisów prawa regulujących świadczenie usług drogą elektroniczną przez Usługodawcę wpływająca na wzajemne prawa i obowiązki określone w umowie zawieranej pomiędzy Klientem a Usługodawcą lub zmiana sposobu świadczenia usług spowodowana wyłącznie względami technicznymi.</li>
          <li>Usługodawca może wypowiedzieć Klientowi Umowę o Świadczenie Usług za 14-dniowym okresem wypowiedzenia lub odmówić mu dalszego prawa do korzystania ze Sklepu z ważnych powodów, w szczególności w przypadku rażącego naruszenia przez Klienta niniejszego Regulaminu, tj. w sytuacjach, gdy Klient narusza Ogólne Warunki Korzystania ze Sklepu.</li>
        </ol>
        <h2>Ochrona danych osobowych</h2>
        <ol>
          <li>Dane osobowe Klienta są przetwarzane przez Usługodawcę jako administratora danych osobowych.</li>
          <li>Podanie danych osobowych przez Klienta jest dobrowolne, ale niezbędne w celu założenia Konta, korzystania z określonych Usług Elektronicznych, zawarcia Umowy.</li>
          <li>Dodatkowe informacje dotyczące przetwarzania danych są dostępne w Polityce Prywatności na stronie internetowej Sklepu.</li>
        </ol>
        <h2>Punkt kontaktowy</h2>
        <ol>
          <li>Usługodawca wyznacza Punkt kontaktowy służący do komunikacji w sprawach Treści, w szczególności dotyczący ich legalności oraz zgodności z warunkami korzystania z usług Sklepu.</li>
          <li>Korespondencja w ramach Punktu kontaktowego odbywa się elektronicznie za pośrednictwem adresu e-mail info@easygo-english.pl.</li>
          <li>O otrzymaniu korespondencji w ramach Punktu kontaktowego Usługodawca informuje nadawcę korespondencji niezwłocznie nie później niż 14 dni.</li>
        </ol>
        <h2>Postanowienia końcowe</h2>
        <ol>
          <li>Regulamin oraz załączniki do Regulaminu stanowią wzorzec umowny w rozumieniu art. 384 § 1 Ustawy Kodeks cywilny.</li>
          <li>Utrwalenie, zabezpieczenie i udostępnienie istotnych postanowień zawieranej Umowy o Świadczenie Usług następuje poprzez przesłanie wiadomości e-mail na adres podany przez Klienta.</li>
          <li>Utrwalenie, zabezpieczenie, udostępnienie oraz potwierdzenie Klientowi istotnych postanowień zawieranej Umowy następuje poprzez przesłanie Klientowi wiadomości e-mail z potwierdzeniem złożonego Zamówienia oraz przekazaniem aktywnego linku do treści niniejszego Regulaminu w treści wiadomości e-mail.</li>
          <li>Dowód dokonania zakupu przez Klienta Sklepu zostanie przekazany za pośrednictwem wiadomości e-mail.</li>
          <li>Treść Regulaminu jest dostępna dla Klientów bezpłatnie na stronie internetowej Sklepu.</li>
          <li>W sprawach nieuregulowanych w niniejszym Regulaminie mają zastosowanie powszechnie obowiązujące przepisy prawa polskiego, w szczególności: Kodeksu Cywilnego oraz inne właściwe przepisy powszechnie obowiązującego prawa.</li>
          <li>Wszelkie spory powstałe pomiędzy Usługodawcą a Klientem niebędącym Konsumentem zostają poddane sądowi właściwemu ze względu na siedzibę Usługodawcy.</li>
          <li>Klient, umieszczając jakiekolwiek treści na Koncie lub w innym miejscu strony internetowej Sklepu, udziela niniejszym Usługodawcy niewyłącznej, nieodpłatnej licencji na wykorzystywanie, utrwalanie w pamięci komputera, zmienianie, usuwanie, uzupełnianie, wykonywanie publiczne, wyświetlanie publiczne, zwielokrotnianie i rozpowszechnianie, w szczególności w Internecie, tych treści, bez ograniczenia terytorialnego.</li>
        </ol>

        <div className="rg-contact">
          <p style={{ margin: 0 }}>Masz pytania? Napisz do nas: <a href="mailto:info@easygo-english.pl">info@easygo-english.pl</a></p>
        </div>
      </div>
    </main>
  );
}
